include: package:pedantic/analysis_options.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: false
    prefer_double_quotes: true

analyzer:
  errors:
    import_of_legacy_library_into_null_safe: ignore
  exclude:
    - lib_old/**/*.dart
