// ---- SHARED ----
interface Attr {
  rank: string;
}

interface Image {
  size: Size;
  "#text": string;
}

type Size = "small" | "medium" | "large" | "extralarge" | "mega";

interface PaginationAttr {
  page: string;
  perPage: string;
  user: string;
  total: string;
  totalPages: string;
}

// ---- TOP ARTISTS ----

export interface LastFmTopArtistsResponse {
  topartists: LastFmTopArtists;
}

export interface LastFmTopArtists {
  artist: Artist[];
  "@attr": PaginationAttr;
}

interface Artist {
  "@attr": Attr;
  mbid: string;
  url: string;
  playcount: string;
  image: Image[];
  name: string;
  streamable: string;
}

// ---- TOP ALBUMS ----

export interface LastFmTopAlbumsResponse {
  topalbums: LastFmTopAlbums;
}

export interface LastFmTopAlbums {
  album: Album[];
  "@attr": PaginationAttr;
}

interface Album {
  artist: Artist;
  "@attr": Attr;
  image: Image[];
  playcount: string;
  url: string;
  name: string;
  mbid: string;
}

// ---- RECENT TRACKS ----

// Generated by https://quicktype.io

export interface LastFmRecentTracksResponse {
  recenttracks: LastFmRecentTracks;
}

export interface LastFmRecentTracks {
  "@attr": PaginationAttr;
  track: Track[];
}

interface Track {
  artist: {
    mbid: string;
    "#text": string;
  };
  "@attr"?: {
    nowplaying: string;
  };
  mbid: string;
  album: {
    mbid: string;
    "#text": string;
  };
  streamable: string;
  url: string;
  name: string;
  image: Image[];
  date?: {
    uts: string;
    "#text": string;
  };
}
